
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.diagramasdeflujo.analizadores;

import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class DiagramaParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public DiagramaParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public DiagramaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public DiagramaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\072\000\002\002\004\000\002\005\005\000\002\005" +
    "\005\000\002\012\005\000\002\013\004\000\002\013\004" +
    "\000\002\013\003\000\002\013\003\000\002\016\005\000" +
    "\002\016\007\000\002\016\005\000\002\016\005\000\002" +
    "\016\005\000\002\016\004\000\002\014\003\000\002\014" +
    "\003\000\002\007\011\000\002\010\011\000\002\020\003" +
    "\000\002\020\004\000\002\015\004\000\002\015\003\000" +
    "\002\017\003\000\002\017\004\000\002\024\005\000\002" +
    "\024\005\000\002\011\005\000\002\011\006\000\002\021" +
    "\005\000\002\021\005\000\002\021\003\000\002\022\005" +
    "\000\002\022\005\000\002\022\003\000\002\023\003\000" +
    "\002\023\003\000\002\023\003\000\002\023\005\000\002" +
    "\006\004\000\002\006\003\000\002\025\006\000\002\025" +
    "\010\000\002\025\010\000\002\025\010\000\002\025\010" +
    "\000\002\025\010\000\002\025\004\000\002\026\003\000" +
    "\002\026\007\000\002\002\005\000\002\002\005\000\002" +
    "\002\003\000\002\003\005\000\002\003\005\000\002\003" +
    "\003\000\002\004\003\000\002\004\003\000\002\004\005" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\217\000\006\003\004\026\006\001\002\000\004\012" +
    "\220\001\002\000\004\002\217\001\002\000\016\003\115" +
    "\017\112\020\107\021\113\022\116\023\117\001\002\000" +
    "\004\012\010\001\002\000\020\003\020\013\015\042\012" +
    "\043\011\044\016\045\013\050\014\001\002\000\004\014" +
    "\100\001\002\000\004\014\065\001\002\000\004\014\060" +
    "\001\002\000\004\014\034\001\002\000\004\014\031\001" +
    "\002\000\004\014\024\001\002\000\022\002\000\003\020" +
    "\013\015\042\012\043\011\044\016\045\013\050\014\001" +
    "\002\000\004\015\022\001\002\000\022\002\uffda\003\uffda" +
    "\013\uffda\042\uffda\043\uffda\044\uffda\045\uffda\050\uffda\001" +
    "\002\000\022\002\uffd3\003\uffd3\013\uffd3\042\uffd3\043\uffd3" +
    "\044\uffd3\045\uffd3\050\uffd3\001\002\000\022\002\uffdb\003" +
    "\uffdb\013\uffdb\042\uffdb\043\uffdb\044\uffdb\045\uffdb\050\uffdb" +
    "\001\002\000\004\046\025\001\002\000\004\016\026\001" +
    "\002\000\004\041\027\001\002\000\004\015\030\001\002" +
    "\000\022\002\uffd6\003\uffd6\013\uffd6\042\uffd6\043\uffd6\044" +
    "\uffd6\045\uffd6\050\uffd6\001\002\000\004\041\032\001\002" +
    "\000\004\015\033\001\002\000\022\002\uffd9\003\uffd9\013" +
    "\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\050\uffd9\001\002" +
    "\000\010\010\040\041\035\051\042\001\002\000\032\004" +
    "\uffca\005\uffca\006\uffca\007\uffca\011\uffca\015\uffca\016\uffca" +
    "\033\uffca\034\uffca\035\uffca\040\uffca\055\uffca\001\002\000" +
    "\020\004\uffce\005\uffce\006\052\007\051\011\uffce\016\uffce" +
    "\040\uffce\001\002\000\032\004\uffcb\005\uffcb\006\uffcb\007" +
    "\uffcb\011\uffcb\015\uffcb\016\uffcb\033\uffcb\034\uffcb\035\uffcb" +
    "\040\uffcb\055\uffcb\001\002\000\010\010\040\041\035\051" +
    "\042\001\002\000\010\004\043\005\044\016\045\001\002" +
    "\000\032\004\uffc9\005\uffc9\006\uffc9\007\uffc9\011\uffc9\015" +
    "\uffc9\016\uffc9\033\uffc9\034\uffc9\035\uffc9\040\uffc9\055\uffc9" +
    "\001\002\000\010\010\040\041\035\051\042\001\002\000" +
    "\010\010\040\041\035\051\042\001\002\000\004\041\046" +
    "\001\002\000\004\015\047\001\002\000\022\002\uffd4\003" +
    "\uffd4\013\uffd4\042\uffd4\043\uffd4\044\uffd4\045\uffd4\050\uffd4" +
    "\001\002\000\020\004\uffcf\005\uffcf\006\052\007\051\011" +
    "\uffcf\016\uffcf\040\uffcf\001\002\000\010\010\040\041\035" +
    "\051\042\001\002\000\010\010\040\041\035\051\042\001" +
    "\002\000\032\004\uffcd\005\uffcd\006\uffcd\007\uffcd\011\uffcd" +
    "\015\uffcd\016\uffcd\033\uffcd\034\uffcd\035\uffcd\040\uffcd\055" +
    "\uffcd\001\002\000\032\004\uffcc\005\uffcc\006\uffcc\007\uffcc" +
    "\011\uffcc\015\uffcc\016\uffcc\033\uffcc\034\uffcc\035\uffcc\040" +
    "\uffcc\055\uffcc\001\002\000\020\004\uffd0\005\uffd0\006\052" +
    "\007\051\011\uffd0\016\uffd0\040\uffd0\001\002\000\010\004" +
    "\043\005\044\011\057\001\002\000\032\004\uffc8\005\uffc8" +
    "\006\uffc8\007\uffc8\011\uffc8\015\uffc8\016\uffc8\033\uffc8\034" +
    "\uffc8\035\uffc8\040\uffc8\055\uffc8\001\002\000\004\047\061" +
    "\001\002\000\004\016\062\001\002\000\004\041\063\001" +
    "\002\000\004\015\064\001\002\000\022\002\uffd5\003\uffd5" +
    "\013\uffd5\042\uffd5\043\uffd5\044\uffd5\045\uffd5\050\uffd5\001" +
    "\002\000\012\010\040\041\035\051\042\052\066\001\002" +
    "\000\004\016\uffd2\001\002\000\004\016\075\001\002\000" +
    "\010\004\043\005\044\040\071\001\002\000\010\010\040" +
    "\041\035\051\042\001\002\000\010\004\043\005\044\040" +
    "\073\001\002\000\010\010\040\041\035\051\042\001\002" +
    "\000\010\004\043\005\044\016\uffd1\001\002\000\004\041" +
    "\076\001\002\000\004\015\077\001\002\000\022\002\uffd8" +
    "\003\uffd8\013\uffd8\042\uffd8\043\uffd8\044\uffd8\045\uffd8\050" +
    "\uffd8\001\002\000\012\010\040\041\035\051\042\052\066" +
    "\001\002\000\004\016\102\001\002\000\004\041\103\001" +
    "\002\000\004\015\104\001\002\000\022\002\uffd7\003\uffd7" +
    "\013\uffd7\042\uffd7\043\uffd7\044\uffd7\045\uffd7\050\uffd7\001" +
    "\002\000\020\003\ufff2\017\ufff2\020\ufff2\021\ufff2\022\ufff2" +
    "\023\ufff2\027\ufff2\001\002\000\020\003\ufffb\017\ufffb\020" +
    "\ufffb\021\ufffb\022\ufffb\023\ufffb\027\ufffb\001\002\000\006" +
    "\053\213\054\214\001\002\000\020\003\115\017\112\020" +
    "\107\021\113\022\116\023\117\027\211\001\002\000\020" +
    "\003\ufffa\017\ufffa\020\ufffa\021\ufffa\022\ufffa\023\ufffa\027" +
    "\ufffa\001\002\000\004\053\203\001\002\000\004\053\201" +
    "\001\002\000\020\003\ufff3\017\ufff3\020\ufff3\021\ufff3\022" +
    "\ufff3\023\ufff3\027\ufff3\001\002\000\004\015\200\001\002" +
    "\000\004\010\167\001\002\000\004\010\120\001\002\000" +
    "\012\010\040\032\121\041\035\051\042\001\002\000\004" +
    "\010\164\001\002\000\022\006\052\007\051\011\uffe3\015" +
    "\uffe3\033\uffe3\034\uffe3\035\uffe3\055\uffe3\001\002\000\006" +
    "\011\151\033\152\001\002\000\010\034\131\035\130\055" +
    "\132\001\002\000\004\033\126\001\002\000\012\010\040" +
    "\032\121\041\035\051\042\001\002\000\006\011\uffe9\033" +
    "\uffe9\001\002\000\012\010\135\041\134\051\141\053\140" +
    "\001\002\000\012\010\135\041\134\051\141\053\140\001" +
    "\002\000\010\010\040\041\035\051\042\001\002\000\012" +
    "\011\uffe7\033\uffe7\034\131\035\130\001\002\000\022\011" +
    "\uffdf\015\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\037\uffdf" +
    "\055\uffdf\001\002\000\010\010\040\041\035\051\042\001" +
    "\002\000\022\011\uffe5\015\uffe5\033\uffe5\034\uffe5\035\uffe5" +
    "\036\142\037\143\055\uffe5\001\002\000\022\011\uffe0\015" +
    "\uffe0\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0\055\uffe0" +
    "\001\002\000\022\011\uffdd\015\uffdd\033\uffdd\034\uffdd\035" +
    "\uffdd\036\uffdd\037\uffdd\055\uffdd\001\002\000\022\011\uffde" +
    "\015\uffde\033\uffde\034\uffde\035\uffde\036\uffde\037\uffde\055" +
    "\uffde\001\002\000\012\010\135\041\134\051\141\053\140" +
    "\001\002\000\012\010\135\041\134\051\141\053\140\001" +
    "\002\000\022\011\uffe1\015\uffe1\033\uffe1\034\uffe1\035\uffe1" +
    "\036\uffe1\037\uffe1\055\uffe1\001\002\000\022\011\uffe2\015" +
    "\uffe2\033\uffe2\034\uffe2\035\uffe2\036\uffe2\037\uffe2\055\uffe2" +
    "\001\002\000\010\011\147\034\131\035\130\001\002\000" +
    "\022\011\uffdc\015\uffdc\033\uffdc\034\uffdc\035\uffdc\036\uffdc" +
    "\037\uffdc\055\uffdc\001\002\000\022\011\uffe4\015\uffe4\033" +
    "\uffe4\034\uffe4\035\uffe4\036\142\037\143\055\uffe4\001\002" +
    "\000\004\025\154\001\002\000\012\010\040\032\121\041" +
    "\035\051\042\001\002\000\006\011\uffe8\033\uffe8\001\002" +
    "\000\012\003\115\017\112\020\107\021\113\001\002\000" +
    "\020\003\uffec\017\uffec\020\uffec\021\uffec\027\uffec\030\uffec" +
    "\031\uffec\001\002\000\016\003\115\017\112\020\107\021" +
    "\113\027\161\031\157\001\002\000\020\003\uffef\017\uffef" +
    "\020\uffef\021\uffef\022\uffef\023\uffef\027\uffef\001\002\000" +
    "\020\003\uffed\017\uffed\020\uffed\021\uffed\027\uffed\030\uffed" +
    "\031\uffed\001\002\000\004\023\163\001\002\000\020\003" +
    "\ufff0\017\ufff0\020\ufff0\021\ufff0\022\ufff0\023\ufff0\027\ufff0" +
    "\001\002\000\020\003\uffee\017\uffee\020\uffee\021\uffee\022" +
    "\uffee\023\uffee\027\uffee\001\002\000\012\010\040\032\121" +
    "\041\035\051\042\001\002\000\004\011\166\001\002\000" +
    "\006\011\uffe6\033\uffe6\001\002\000\012\010\040\032\121" +
    "\041\035\051\042\001\002\000\006\011\171\033\152\001" +
    "\002\000\004\024\172\001\002\000\012\003\115\017\112" +
    "\020\107\021\113\001\002\000\016\003\115\017\112\020" +
    "\107\021\113\027\174\030\175\001\002\000\004\022\177" +
    "\001\002\000\020\003\uffeb\017\uffeb\020\uffeb\021\uffeb\022" +
    "\uffeb\023\uffeb\027\uffeb\001\002\000\020\003\ufff1\017\ufff1" +
    "\020\ufff1\021\ufff1\022\ufff1\023\ufff1\027\ufff1\001\002\000" +
    "\020\003\uffea\017\uffea\020\uffea\021\uffea\022\uffea\023\uffea" +
    "\027\uffea\001\002\000\024\003\ufff4\017\ufff4\020\ufff4\021" +
    "\ufff4\022\ufff4\023\ufff4\027\ufff4\030\ufff4\031\ufff4\001\002" +
    "\000\004\015\202\001\002\000\024\003\ufff5\017\ufff5\020" +
    "\ufff5\021\ufff5\022\ufff5\023\ufff5\027\ufff5\030\ufff5\031\ufff5" +
    "\001\002\000\006\014\204\015\205\001\002\000\010\010" +
    "\040\041\035\051\042\001\002\000\024\003\ufff9\017\ufff9" +
    "\020\ufff9\021\ufff9\022\ufff9\023\ufff9\027\ufff9\030\ufff9\031" +
    "\ufff9\001\002\000\010\015\207\034\131\035\130\001\002" +
    "\000\024\003\ufff8\017\ufff8\020\ufff8\021\ufff8\022\ufff8\023" +
    "\ufff8\027\ufff8\030\ufff8\031\ufff8\001\002\000\020\003\ufffc" +
    "\017\ufffc\020\ufffc\021\ufffc\022\ufffc\023\ufffc\027\ufffc\001" +
    "\002\000\004\012\ufffe\001\002\000\020\003\ufffd\017\ufffd" +
    "\020\ufffd\021\ufffd\022\ufffd\023\ufffd\027\ufffd\001\002\000" +
    "\004\015\216\001\002\000\004\015\215\001\002\000\024" +
    "\003\ufff6\017\ufff6\020\ufff6\021\ufff6\022\ufff6\023\ufff6\027" +
    "\ufff6\030\ufff6\031\ufff6\001\002\000\024\003\ufff7\017\ufff7" +
    "\020\ufff7\021\ufff7\022\ufff7\023\ufff7\027\ufff7\030\ufff7\031" +
    "\ufff7\001\002\000\004\002\001\001\002\000\020\003\020" +
    "\013\015\042\012\043\011\044\016\045\013\050\014\001" +
    "\002\000\022\002\uffff\003\020\013\015\042\012\043\011" +
    "\044\016\045\013\050\014\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\217\000\006\005\004\012\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\007\113\010\104\013\107" +
    "\014\105\016\110\001\001\000\002\001\001\000\006\006" +
    "\016\025\020\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\025\022\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\002\040\003\035\004\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\002\055\003\035\004\036\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\003\054\004\036\001" +
    "\001\000\006\003\047\004\036\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\004\053\001\001\000\004\004\052\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\002\067\003\035\004\036\026\066\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\002" +
    "\071\003\035\004\036\001\001\000\002\001\001\000\010" +
    "\002\073\003\035\004\036\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\002\067\003\035\004\036\026\100\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\007\113\010\104\014\207\016\211\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\003\121\004\036\011\124\021\123\024\122\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\003\121\004" +
    "\036\011\126\021\123\001\001\000\002\001\001\000\006" +
    "\022\147\023\136\001\001\000\006\022\135\023\136\001" +
    "\001\000\010\003\121\004\036\021\132\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\121\004\036\021" +
    "\145\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\023\144\001\001\000" +
    "\004\023\143\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\003\121\004\036\011\152\021\123" +
    "\001\001\000\002\001\001\000\006\015\155\016\154\001" +
    "\001\000\002\001\001\000\006\016\157\020\161\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\003\121\004\036" +
    "\011\164\021\123\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\003\121\004\036\011\124\021\123\024\167" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\015" +
    "\172\016\154\001\001\000\006\016\157\017\175\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\121\004\036\021" +
    "\205\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\006\220\025" +
    "\020\001\001\000\004\025\022\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$DiagramaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$DiagramaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$DiagramaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$DiagramaParser$actions {
  private final DiagramaParser parser;

  /** Constructor */
  CUP$DiagramaParser$actions(DiagramaParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$DiagramaParser$do_action_part00000000(
    int                        CUP$DiagramaParser$act_num,
    java_cup.runtime.lr_parser CUP$DiagramaParser$parser,
    java.util.Stack            CUP$DiagramaParser$stack,
    int                        CUP$DiagramaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$DiagramaParser$result;

      /* select the action based on the action number */
      switch (CUP$DiagramaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= codigo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		RESULT = start_val;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$DiagramaParser$parser.done_parsing();
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // codigo ::= pseudocodigo SEPARADOR configuracion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("codigo",3, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // codigo ::= error SEPARADOR configuracion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("codigo",3, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // pseudocodigo ::= INICIO instrucciones FIN 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("pseudocodigo",8, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instrucciones ::= instrucciones ciclo 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instrucciones ::= ciclo 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instruccion ::= VAR IDENT DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= VAR IDENT ASIGNACION expr2 DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= MOSTRAR IDENT DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= MOSTRAR CADENA DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= LEER IDENT DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion ::= error DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // ciclo ::= mientras 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("ciclo",10, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ciclo ::= condicional 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("ciclo",10, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // mientras ::= MIENTRAS PARENAPER condiciones PARENCERRA HACER bloque finalmientras 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("mientras",5, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicional ::= SI PARENAPER condiciones PARENCERRA ENTONCES bloque fincondicional 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicional",6, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // fincondicional ::= FINSI 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("fincondicional",14, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // fincondicional ::= FIN SI 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("fincondicional",14, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // bloque ::= bloque instruccion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("bloque",11, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // bloque ::= instruccion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("bloque",11, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // finalmientras ::= FINMIENTRAS 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("finalmientras",13, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // finalmientras ::= FIN MIENTRAS 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("finalmientras",13, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // condiciones ::= condicion OPERALOG condicion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condiciones",18, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // condiciones ::= condiciones OPERALOG condicion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condiciones",18, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // condicion ::= expr2 OPERARELA expr2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicion",7, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // condicion ::= OPERALOGNEG PARENAPER condicion PARENCERRA 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicion",7, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr2 ::= expr2 SUMA term2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr2 ::= expr2 RESTA term2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr2 ::= term 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // term2 ::= term2 MULTI factor2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",16, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // term2 ::= term2 DIVI factor2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",16, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // term2 ::= factor2 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",16, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // factor2 ::= NUMERO 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // factor2 ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // factor2 ::= IDENT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // factor2 ::= PARENAPER expr2 PARENCERRA 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // configuracion ::= configuracion instruccion_config 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("configuracion",4, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // configuracion ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("configuracion",4, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // instruccion_config ::= DEFAULT ASIGNACION NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // instruccion_config ::= COLORTEXTO ASIGNACION color ASIGINDI NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // instruccion_config ::= COLOR ASIGNACION color ASIGINDI NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // instruccion_config ::= FIGURA ASIGNACION TFIGURA ASIGINDI NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= LETRA ASIGNACION TLETRA ASIGINDI NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= LETRASIZE ASIGNACION expr ASIGINDI NUMERO DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= error DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // color ::= HEXADECIMAL 
            {
              String RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("color",20, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // color ::= expr COMA expr COMA expr 
            {
              String RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("color",20, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr MAS term 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr MENOS term 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= term 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // term ::= term POR factor 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // term ::= term SIGNODIVI factor 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // term ::= factor 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // factor ::= NUMERO 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // factor ::= DECIMAL 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // factor ::= PARENAPER expr PARENCERRA 
            {
              Double RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$DiagramaParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$DiagramaParser$do_action(
    int                        CUP$DiagramaParser$act_num,
    java_cup.runtime.lr_parser CUP$DiagramaParser$parser,
    java.util.Stack            CUP$DiagramaParser$stack,
    int                        CUP$DiagramaParser$top)
    throws java.lang.Exception
    {
              return CUP$DiagramaParser$do_action_part00000000(
                               CUP$DiagramaParser$act_num,
                               CUP$DiagramaParser$parser,
                               CUP$DiagramaParser$stack,
                               CUP$DiagramaParser$top);
    }
}

}
