
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.diagramasdeflujo.analizadores;

import com.example.diagramasdeflujo.enums.TipoEnum;
import com.example.diagramasdeflujo.enums.Inst;
import com.example.diagramasdeflujo.enums.Letra;
import com.example.diagramasdeflujo.enums.Figura;
import com.example.diagramasdeflujo.backend.MensajeError;
import com.example.diagramasdeflujo.backend.Pseudocodigo;
import com.example.diagramasdeflujo.backend.OperadorMat;
import com.example.diagramasdeflujo.backend.estructuras.Bloque;
import com.example.diagramasdeflujo.backend.estructuras.Mientras;
import com.example.diagramasdeflujo.backend.estructuras.Si;
import com.example.diagramasdeflujo.backend.ReporteEstructura;
import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class DiagramaParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public DiagramaParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public DiagramaParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public DiagramaParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\100\000\002\002\004\000\002\005\006\000\002\005" +
    "\006\000\002\011\005\000\002\011\005\000\002\012\004" +
    "\000\002\012\004\000\002\012\003\000\002\012\003\000" +
    "\002\021\005\000\002\021\007\000\002\021\005\000\002" +
    "\021\005\000\002\021\005\000\002\021\006\000\002\021" +
    "\004\000\002\013\003\000\002\013\003\000\002\007\011" +
    "\000\002\007\005\000\002\010\011\000\002\010\005\000" +
    "\002\015\003\000\002\015\004\000\002\020\004\000\002" +
    "\020\003\000\002\014\003\000\002\014\004\000\002\023" +
    "\003\000\002\023\005\000\002\024\005\000\002\024\006" +
    "\000\002\025\005\000\002\025\005\000\002\025\003\000" +
    "\002\026\005\000\002\026\005\000\002\026\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\005\000\002\006\004\000\002\006\003\000\002\016\006" +
    "\000\002\016\010\000\002\016\010\000\002\016\010\000" +
    "\002\016\010\000\002\016\010\000\002\016\004\000\002" +
    "\017\003\000\002\017\004\000\002\022\003\000\002\022" +
    "\007\000\002\002\005\000\002\002\005\000\002\002\003" +
    "\000\002\003\005\000\002\003\005\000\002\003\003\000" +
    "\002\004\003\000\002\004\003\000\002\004\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\006\003\004\026\006\001\002\000\004\012" +
    "\233\001\002\000\004\002\232\001\002\000\020\003\121" +
    "\017\116\020\113\021\117\022\122\023\123\053\112\001" +
    "\002\000\004\012\010\001\002\000\004\015\011\001\002" +
    "\000\020\003\021\013\016\041\013\042\012\043\017\044" +
    "\014\045\015\001\002\000\004\014\103\001\002\000\004" +
    "\014\070\001\002\000\004\014\063\001\002\000\004\014" +
    "\037\001\002\000\004\014\034\001\002\000\004\014\025" +
    "\001\002\000\022\002\000\003\021\013\016\041\013\042" +
    "\012\043\017\044\014\045\015\001\002\000\004\015\023" +
    "\001\002\000\022\002\uffd6\003\uffd6\013\uffd6\041\uffd6\042" +
    "\uffd6\043\uffd6\044\uffd6\045\uffd6\001\002\000\022\002\uffcf" +
    "\003\uffcf\013\uffcf\041\uffcf\042\uffcf\043\uffcf\044\uffcf\045" +
    "\uffcf\001\002\000\022\002\uffd7\003\uffd7\013\uffd7\041\uffd7" +
    "\042\uffd7\043\uffd7\044\uffd7\045\uffd7\001\002\000\004\046" +
    "\026\001\002\000\004\016\027\001\002\000\004\047\030" +
    "\001\002\000\004\015\032\001\002\000\024\002\uffd2\003" +
    "\uffd2\013\uffd2\015\033\041\uffd2\042\uffd2\043\uffd2\044\uffd2" +
    "\045\uffd2\001\002\000\024\002\uffce\003\uffce\013\uffce\015" +
    "\uffce\041\uffce\042\uffce\043\uffce\044\uffce\045\uffce\001\002" +
    "\000\024\002\uffcd\003\uffcd\013\uffcd\015\uffcd\041\uffcd\042" +
    "\uffcd\043\uffcd\044\uffcd\045\uffcd\001\002\000\004\047\035" +
    "\001\002\000\004\015\032\001\002\000\024\002\uffd5\003" +
    "\uffd5\013\uffd5\015\033\041\uffd5\042\uffd5\043\uffd5\044\uffd5" +
    "\045\uffd5\001\002\000\010\010\043\047\040\050\045\001" +
    "\002\000\020\004\uffc4\005\uffc4\006\uffc4\007\uffc4\011\uffc4" +
    "\016\uffc4\040\uffc4\001\002\000\020\004\uffc8\005\uffc8\006" +
    "\055\007\054\011\uffc8\016\uffc8\040\uffc8\001\002\000\020" +
    "\004\uffc5\005\uffc5\006\uffc5\007\uffc5\011\uffc5\016\uffc5\040" +
    "\uffc5\001\002\000\010\010\043\047\040\050\045\001\002" +
    "\000\010\004\046\005\047\016\050\001\002\000\020\004" +
    "\uffc3\005\uffc3\006\uffc3\007\uffc3\011\uffc3\016\uffc3\040\uffc3" +
    "\001\002\000\010\010\043\047\040\050\045\001\002\000" +
    "\010\010\043\047\040\050\045\001\002\000\004\047\051" +
    "\001\002\000\004\015\032\001\002\000\024\002\uffd0\003" +
    "\uffd0\013\uffd0\015\033\041\uffd0\042\uffd0\043\uffd0\044\uffd0" +
    "\045\uffd0\001\002\000\020\004\uffc9\005\uffc9\006\055\007" +
    "\054\011\uffc9\016\uffc9\040\uffc9\001\002\000\010\010\043" +
    "\047\040\050\045\001\002\000\010\010\043\047\040\050" +
    "\045\001\002\000\020\004\uffc7\005\uffc7\006\uffc7\007\uffc7" +
    "\011\uffc7\016\uffc7\040\uffc7\001\002\000\020\004\uffc6\005" +
    "\uffc6\006\uffc6\007\uffc6\011\uffc6\016\uffc6\040\uffc6\001\002" +
    "\000\020\004\uffca\005\uffca\006\055\007\054\011\uffca\016" +
    "\uffca\040\uffca\001\002\000\010\004\046\005\047\011\062" +
    "\001\002\000\020\004\uffc2\005\uffc2\006\uffc2\007\uffc2\011" +
    "\uffc2\016\uffc2\040\uffc2\001\002\000\004\051\064\001\002" +
    "\000\004\016\065\001\002\000\004\047\066\001\002\000" +
    "\004\015\032\001\002\000\024\002\uffd1\003\uffd1\013\uffd1" +
    "\015\033\041\uffd1\042\uffd1\043\uffd1\044\uffd1\045\uffd1\001" +
    "\002\000\012\010\043\047\040\050\045\052\071\001\002" +
    "\000\004\016\uffcc\001\002\000\004\016\100\001\002\000" +
    "\010\004\046\005\047\040\074\001\002\000\010\010\043" +
    "\047\040\050\045\001\002\000\010\004\046\005\047\040" +
    "\076\001\002\000\010\010\043\047\040\050\045\001\002" +
    "\000\010\004\046\005\047\016\uffcb\001\002\000\004\047" +
    "\101\001\002\000\004\015\032\001\002\000\024\002\uffd4" +
    "\003\uffd4\013\uffd4\015\033\041\uffd4\042\uffd4\043\uffd4\044" +
    "\uffd4\045\uffd4\001\002\000\012\010\043\047\040\050\045" +
    "\052\071\001\002\000\004\016\105\001\002\000\004\047" +
    "\106\001\002\000\004\015\032\001\002\000\024\002\uffd3" +
    "\003\uffd3\013\uffd3\015\033\041\uffd3\042\uffd3\043\uffd3\044" +
    "\uffd3\045\uffd3\001\002\000\022\003\ufff0\017\ufff0\020\ufff0" +
    "\021\ufff0\022\ufff0\023\ufff0\027\ufff0\053\ufff0\001\002\000" +
    "\022\003\ufffa\017\ufffa\020\ufffa\021\ufffa\022\ufffa\023\ufffa" +
    "\027\ufffa\053\ufffa\001\002\000\004\014\227\001\002\000" +
    "\006\053\223\054\224\001\002\000\022\003\160\017\116" +
    "\020\113\021\117\022\122\023\123\027\221\053\112\001" +
    "\002\000\022\003\ufff9\017\ufff9\020\ufff9\021\ufff9\022\ufff9" +
    "\023\ufff9\027\ufff9\053\ufff9\001\002\000\004\053\213\001" +
    "\002\000\004\053\211\001\002\000\022\003\ufff1\017\ufff1" +
    "\020\ufff1\021\ufff1\022\ufff1\023\ufff1\027\ufff1\053\ufff1\001" +
    "\002\000\006\015\170\027\210\001\002\000\006\003\175" +
    "\010\176\001\002\000\006\003\124\010\125\001\002\000" +
    "\006\027\163\031\166\001\002\000\014\010\137\032\130" +
    "\047\135\050\126\053\127\001\002\000\022\011\uffda\015" +
    "\uffda\033\uffda\034\uffda\035\uffda\036\uffda\037\uffda\055\uffda" +
    "\001\002\000\022\011\uffd9\015\uffd9\033\uffd9\034\uffd9\035" +
    "\uffd9\036\uffd9\037\uffd9\055\uffd9\001\002\000\004\010\171" +
    "\001\002\000\022\011\uffdf\015\uffdf\033\uffdf\034\uffdf\035" +
    "\uffdf\036\145\037\146\055\uffdf\001\002\000\006\011\154" +
    "\033\155\001\002\000\010\034\142\035\141\055\152\001" +
    "\002\000\022\011\uffdc\015\uffdc\033\uffdc\034\uffdc\035\uffdc" +
    "\036\uffdc\037\uffdc\055\uffdc\001\002\000\022\011\uffdb\015" +
    "\uffdb\033\uffdb\034\uffdb\035\uffdb\036\uffdb\037\uffdb\055\uffdb" +
    "\001\002\000\006\011\uffe5\033\uffe5\001\002\000\012\010" +
    "\137\047\135\050\126\053\127\001\002\000\010\011\143" +
    "\034\142\035\141\001\002\000\012\010\137\047\135\050" +
    "\126\053\127\001\002\000\012\010\137\047\135\050\126" +
    "\053\127\001\002\000\022\011\uffd8\015\uffd8\033\uffd8\034" +
    "\uffd8\035\uffd8\036\uffd8\037\uffd8\055\uffd8\001\002\000\022" +
    "\011\uffe1\015\uffe1\033\uffe1\034\uffe1\035\uffe1\036\145\037" +
    "\146\055\uffe1\001\002\000\012\010\137\047\135\050\126" +
    "\053\127\001\002\000\012\010\137\047\135\050\126\053" +
    "\127\001\002\000\022\011\uffdd\015\uffdd\033\uffdd\034\uffdd" +
    "\035\uffdd\036\uffdd\037\uffdd\055\uffdd\001\002\000\022\011" +
    "\uffde\015\uffde\033\uffde\034\uffde\035\uffde\036\uffde\037\uffde" +
    "\055\uffde\001\002\000\022\011\uffe0\015\uffe0\033\uffe0\034" +
    "\uffe0\035\uffe0\036\145\037\146\055\uffe0\001\002\000\012" +
    "\010\137\047\135\050\126\053\127\001\002\000\012\011" +
    "\uffe3\033\uffe3\034\142\035\141\001\002\000\004\025\157" +
    "\001\002\000\014\010\137\032\130\047\135\050\126\053" +
    "\127\001\002\000\006\011\uffe4\033\uffe4\001\002\000\014" +
    "\003\160\017\116\020\113\021\117\053\112\001\002\000" +
    "\004\015\170\001\002\000\022\003\uffe8\017\uffe8\020\uffe8" +
    "\021\uffe8\027\uffe8\030\uffe8\031\uffe8\053\uffe8\001\002\000" +
    "\020\003\160\017\116\020\113\021\117\027\163\031\166" +
    "\053\112\001\002\000\004\023\167\001\002\000\022\003" +
    "\uffed\017\uffed\020\uffed\021\uffed\022\uffed\023\uffed\027\uffed" +
    "\053\uffed\001\002\000\022\003\uffe9\017\uffe9\020\uffe9\021" +
    "\uffe9\027\uffe9\030\uffe9\031\uffe9\053\uffe9\001\002\000\022" +
    "\003\uffeb\017\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb\027" +
    "\uffeb\053\uffeb\001\002\000\022\003\uffea\017\uffea\020\uffea" +
    "\021\uffea\022\uffea\023\uffea\027\uffea\053\uffea\001\002\000" +
    "\026\003\ufff2\017\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2" +
    "\027\ufff2\030\ufff2\031\ufff2\053\ufff2\001\002\000\014\010" +
    "\137\032\130\047\135\050\126\053\127\001\002\000\004" +
    "\011\173\001\002\000\006\011\uffe2\033\uffe2\001\002\000" +
    "\022\003\uffec\017\uffec\020\uffec\021\uffec\022\uffec\023\uffec" +
    "\027\uffec\053\uffec\001\002\000\006\027\205\030\203\001" +
    "\002\000\014\010\137\032\130\047\135\050\126\053\127" +
    "\001\002\000\006\011\200\033\155\001\002\000\004\024" +
    "\201\001\002\000\014\003\160\017\116\020\113\021\117" +
    "\053\112\001\002\000\020\003\160\017\116\020\113\021" +
    "\117\027\205\030\203\053\112\001\002\000\022\003\uffe7" +
    "\017\uffe7\020\uffe7\021\uffe7\022\uffe7\023\uffe7\027\uffe7\053" +
    "\uffe7\001\002\000\022\003\uffef\017\uffef\020\uffef\021\uffef" +
    "\022\uffef\023\uffef\027\uffef\053\uffef\001\002\000\004\022" +
    "\206\001\002\000\022\003\uffe6\017\uffe6\020\uffe6\021\uffe6" +
    "\022\uffe6\023\uffe6\027\uffe6\053\uffe6\001\002\000\022\003" +
    "\uffee\017\uffee\020\uffee\021\uffee\022\uffee\023\uffee\027\uffee" +
    "\053\uffee\001\002\000\004\012\ufffd\001\002\000\004\015" +
    "\212\001\002\000\026\003\ufff4\017\ufff4\020\ufff4\021\ufff4" +
    "\022\ufff4\023\ufff4\027\ufff4\030\ufff4\031\ufff4\053\ufff4\001" +
    "\002\000\006\014\214\015\215\001\002\000\012\010\137" +
    "\047\135\050\126\053\127\001\002\000\026\003\ufff8\017" +
    "\ufff8\020\ufff8\021\ufff8\022\ufff8\023\ufff8\027\ufff8\030\ufff8" +
    "\031\ufff8\053\ufff8\001\002\000\010\015\217\034\142\035" +
    "\141\001\002\000\026\003\ufff7\017\ufff7\020\ufff7\021\ufff7" +
    "\022\ufff7\023\ufff7\027\ufff7\030\ufff7\031\ufff7\053\ufff7\001" +
    "\002\000\022\003\ufffb\017\ufffb\020\ufffb\021\ufffb\022\ufffb" +
    "\023\ufffb\027\ufffb\053\ufffb\001\002\000\004\012\ufffe\001" +
    "\002\000\022\003\ufffc\017\ufffc\020\ufffc\021\ufffc\022\ufffc" +
    "\023\ufffc\027\ufffc\053\ufffc\001\002\000\004\015\226\001" +
    "\002\000\004\015\225\001\002\000\026\003\ufff5\017\ufff5" +
    "\020\ufff5\021\ufff5\022\ufff5\023\ufff5\027\ufff5\030\ufff5\031" +
    "\ufff5\053\ufff5\001\002\000\026\003\ufff6\017\ufff6\020\ufff6" +
    "\021\ufff6\022\ufff6\023\ufff6\027\ufff6\030\ufff6\031\ufff6\053" +
    "\ufff6\001\002\000\012\010\137\047\135\050\126\053\127" +
    "\001\002\000\010\015\231\034\142\035\141\001\002\000" +
    "\026\003\ufff3\017\ufff3\020\ufff3\021\ufff3\022\ufff3\023\ufff3" +
    "\027\ufff3\030\ufff3\031\ufff3\053\ufff3\001\002\000\004\002" +
    "\001\001\002\000\004\015\234\001\002\000\020\003\021" +
    "\013\016\041\013\042\012\043\017\044\014\045\015\001" +
    "\002\000\022\002\uffff\003\021\013\016\041\013\042\012" +
    "\043\017\044\014\045\015\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\006\005\004\011\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\007\117\010\107\012\113" +
    "\013\110\021\114\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\006\017\016\021\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\016\023\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\017\030\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\017\035\001\001\000\002\001\001\000\010\002\043\003" +
    "\040\004\041\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\002\060\003\040\004\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\003\057" +
    "\004\041\001\001\000\006\003\052\004\041\001\001\000" +
    "\002\001\001\000\004\017\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\056\001\001\000\004\004" +
    "\055\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\017\066" +
    "\001\001\000\002\001\001\000\012\002\072\003\040\004" +
    "\041\022\071\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\002\074\003\040\004\041\001" +
    "\001\000\002\001\001\000\010\002\076\003\040\004\041" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\101\001\001\000\002\001\001\000\012\002\072\003\040" +
    "\004\041\022\103\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\017\106\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\007\117\010\107\013\217\021\221\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\173\001\001\000\014\023\131\024" +
    "\135\025\132\026\130\027\133\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\025\137\026\130\027" +
    "\133\001\001\000\002\001\001\000\006\026\150\027\133" +
    "\001\001\000\006\026\143\027\133\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\027\147\001\001\000\004" +
    "\027\146\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\025\152\026\130\027\133\001\001" +
    "\000\002\001\001\000\002\001\001\000\012\024\155\025" +
    "\132\026\130\027\133\001\001\000\002\001\001\000\006" +
    "\020\161\021\160\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\163\021\164\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\012\024\171\025\132" +
    "\026\130\027\133\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\014\206\001\001\000\014" +
    "\023\176\024\135\025\132\026\130\027\133\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\020\201\021\160" +
    "\001\001\000\006\014\203\021\164\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\025\215\026\130" +
    "\027\133\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\025\227\026\130\027\133" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\234\016\021\001\001" +
    "\000\004\016\023\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$DiagramaParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$DiagramaParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$DiagramaParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private DiagramaLexer lex;
    private List<MensajeError> syntaxErrors;
    private Pseudocodigo pseudo;

    public DiagramaParser(DiagramaLexer lex, Pseudocodigo pseudo){
        super(lex);
        this.syntaxErrors = pseudo.getErrores();
        this.pseudo = pseudo;
    }

    public void agregarTexto(StringBuilder texto, List<String> cadenas){
    	for(String cadena: cadenas){
    		texto.append(cadena);
    	}
    }
    
    public String pasarATexto(List<String> lista){
    	StringBuilder texto = new StringBuilder();
    	agregarTexto(texto, lista);
    	return texto.toString();
    }

    public DiagramaLexer getLexer(){
        return this.lex;
    }

    public List<MensajeError> getSyntaxErrors(){
        return this.syntaxErrors;
    }

    public void syntax_error(Symbol cur_token){
        MensajeError error = new MensajeError(TipoEnum.SINTACTICO);
        
        if(cur_token.value != null) {
        	error.setLexema(cur_token.value.toString());
        } else {
        	error.setLexema(symbl_name_from_id(cur_token.sym));
        }
	error.setLinea(cur_token.left);
	error.setColumna(cur_token.right);
        
        if( expected_token_ids().isEmpty()  ){
        	error.setDescripcion("ya no se esperaba ningún símbolo");
        } else {
        	StringBuilder mssBuilder = new StringBuilder();
            	mssBuilder.append("Se esperaba: ");
            	for(Integer expected_token_id : expected_token_ids() ){ 
                	if(!symbl_name_from_id(expected_token_id).equals("error")){
                    	mssBuilder.append(symbl_name_from_id(expected_token_id));
                    	mssBuilder.append(", ");
                	}
            	}
            	error.setDescripcion(mssBuilder.toString());
        }
        syntaxErrors.add(error);
    }

    public void report_error(String message, Object info){
        try{
            	Symbol cur_token = (Symbol) info;
            	MensajeError error = new MensajeError(TipoEnum.SINTACTICO);
            	if(cur_token != null){
            		error.setLinea(cur_token.left);
            		error.setColumna(cur_token.right);
        		if(cur_token.value != null){
        			error.setLexema(cur_token.value.toString());
        		} else {
        			error.setLexema(symbl_name_from_id(cur_token.sym));
        		}
            	}

            	if(message != null){
                	error.setDescripcion(message);
            	}
            syntaxErrors.add(error);
        } catch (Exception e){
        	MensajeError error = new MensajeError(TipoEnum.SINTACTICO);
        	if(message != null){
                	error.setDescripcion(message);
                	syntaxErrors.add(error);
            	}
        }
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        MensajeError error = new MensajeError(TipoEnum.SINTACTICO);
        String tokenInfo = "";
    if (cur_token != null) {
        tokenInfo += cur_token.left + ", " + cur_token.right;
        // Si tiene valor asociado
        if (cur_token.value != null) {
            tokenInfo += " ('" + cur_token.value + "')";
        }
    }
        error.setDescripcion("Error que no se puede recuperar" + tokenInfo);
        syntaxErrors.add(error);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$DiagramaParser$actions {
  private final DiagramaParser parser;

  /** Constructor */
  CUP$DiagramaParser$actions(DiagramaParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$DiagramaParser$do_action_part00000000(
    int                        CUP$DiagramaParser$act_num,
    java_cup.runtime.lr_parser CUP$DiagramaParser$parser,
    java.util.Stack            CUP$DiagramaParser$stack,
    int                        CUP$DiagramaParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$DiagramaParser$result;

      /* select the action based on the action number */
      switch (CUP$DiagramaParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= codigo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		RESULT = start_val;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$DiagramaParser$parser.done_parsing();
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // codigo ::= pseudocodigo SEPARADOR DELIMIT configuracion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("codigo",3, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // codigo ::= error SEPARADOR DELIMIT configuracion 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("codigo",3, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // pseudocodigo ::= INICIO instrucciones FIN 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("pseudocodigo",7, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // pseudocodigo ::= INICIO error FIN 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("pseudocodigo",7, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 pseudo.agregarInstruccion(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",8, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instrucciones ::= instrucciones ciclo 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",8, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instrucciones ::= ciclo 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",8, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instrucciones ::= instruccion 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 pseudo.agregarInstruccion(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instrucciones",8, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instruccion ::= VAR IDENT DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = "VAR " + n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instruccion ::= VAR IDENT ASIGNACION expr2 DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = "VAR " + n1 + " = " + pasarATexto(n2); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instruccion ::= MOSTRAR IDENT DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = "MOSTRAR " + n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instruccion ::= MOSTRAR CADENA DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = "MOSTRAR " + n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instruccion ::= LEER IDENT DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = "LEER " + n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instruccion ::= IDENT ASIGNACION expr2 DELIMIT 
            {
              String RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = n1 + " = " + pasarATexto(n2); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instruccion ::= error DELIMIT 
            {
              String RESULT =null;
		 RESULT = "Error"; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion",15, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // ciclo ::= mientras 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("ciclo",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ciclo ::= condicional 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("ciclo",9, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // mientras ::= MIENTRAS PARENAPER condiciones PARENCERRA HACER bloque finalmientras 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).right;
		StringBuilder n1 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Bloque n2 = (Bloque)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.agregarAccion(new Mientras(n1.toString(), n2)); 
										pseudo.agregarReporteDeEstructura(new ReporteEstructura(Inst.MIENTRAS, n0left, n1.toString()));
												
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("mientras",5, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // mientras ::= MIENTRAS error finalmientras 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("mientras",5, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // condicional ::= SI PARENAPER condiciones PARENCERRA ENTONCES bloque fincondicional 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).right;
		StringBuilder n1 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Bloque n2 = (Bloque)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.agregarAccion(new Si(n1.toString(), n2));
										pseudo.agregarReporteDeEstructura(new ReporteEstructura(Inst.SI, n0left, n1.toString()));
												
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicional",6, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-6)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // condicional ::= SI error fincondicional 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicional",6, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // fincondicional ::= FINSI 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("fincondicional",11, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // fincondicional ::= FIN SI 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("fincondicional",11, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bloque ::= bloque instruccion 
            {
              Bloque RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Bloque n1 = (Bloque)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n2 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 n1.agregarInstruccion(n2); RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("bloque",14, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bloque ::= instruccion 
            {
              Bloque RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new Bloque(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("bloque",14, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // finalmientras ::= FINMIENTRAS 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("finalmientras",10, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // finalmientras ::= FIN MIENTRAS 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("finalmientras",10, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // condiciones ::= condicion 
            {
              StringBuilder RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		StringBuilder n1 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condiciones",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // condiciones ::= condiciones OPERALOG condicion 
            {
              StringBuilder RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		StringBuilder n1 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n2 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		StringBuilder n3 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1.append(" ").append(n2).append(" ").append(n3); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condiciones",17, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // condicion ::= expr2 OPERARELA expr2 
            {
              StringBuilder RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		String n2 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n3 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 
											RESULT = new StringBuilder(pasarATexto(n1)).append(" ").append(n2).append(pasarATexto(n3)); 
												
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicion",18, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // condicion ::= OPERALOGNEG PARENAPER condicion PARENCERRA 
            {
              StringBuilder RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		StringBuilder n1 = (StringBuilder)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = new StringBuilder("!(").append(n1).append(")"); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("condicion",18, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr2 ::= expr2 SUMA term2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		  
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.get(n1.size()-1), "+", n2.get(0)});
										n1.add(" + "); n1.addAll(n2); RESULT = n1;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr2 ::= expr2 RESTA term2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		  
        									pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.get(n1.size()-1), "-", n2.get(0)});
        									n1.add(" - "); n1.addAll(n2); RESULT = n1;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr2 ::= term2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr2",19, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // term2 ::= term2 MULTI factor2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		  
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.get(n1.size()-1), "*", n2.get(0)});
										n1.add(" * "); n1.addAll(n2); RESULT = n1;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",20, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // term2 ::= term2 DIVI factor2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n2 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 
        									pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.get(n1.size()-1), "/", n2.get(0)});
        									n1.add(" / "); n1.addAll(n2); RESULT = n1;
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",20, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // term2 ::= factor2 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term2",20, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // factor2 ::= NUMERO 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(n1.toString()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",21, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // factor2 ::= DECIMAL 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		Double n1 = (Double)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(n1.toString()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",21, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // factor2 ::= IDENT 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new ArrayList<>(); RESULT.add(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",21, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // factor2 ::= PARENAPER expr2 PARENCERRA 
            {
              List<String> RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		List<String> n1 = (List<String>)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = new ArrayList<>(); RESULT.add("("); RESULT.addAll(n1); RESULT.add(")"); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor2",21, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // configuracion ::= configuracion instruccion_config 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("configuracion",4, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // configuracion ::= instruccion_config 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("configuracion",4, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // instruccion_config ::= DEFAULT ASIGNACION NUMERO delimitador 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.porDefecto(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // instruccion_config ::= COLORTEXTO ASIGNACION color ASIGINDI NUMERO delimitador 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).right;
		DatosConfig n0 = (DatosConfig)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.cambiarColorTexto(n1, n2, n0.getTipo()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // instruccion_config ::= COLOR ASIGNACION color ASIGINDI NUMERO delimitador 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).right;
		DatosConfig n0 = (DatosConfig)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		Object n1 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.cambiarColor(n1, n2, n0.getTipo()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // instruccion_config ::= FIGURA ASIGNACION TFIGURA ASIGINDI NUMERO delimitador 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).right;
		DatosConfig n0 = (DatosConfig)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		Figura n1 = (Figura)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.cambiarFigura(n1, n2, n0.getTipo()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // instruccion_config ::= LETRA ASIGNACION TLETRA ASIGINDI NUMERO delimitador 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).right;
		DatosConfig n0 = (DatosConfig)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		Letra n1 = (Letra)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.cambiarLetra(n1, n2, n0.getTipo()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // instruccion_config ::= LETRASIZE ASIGNACION expr ASIGINDI NUMERO delimitador 
            {
              Object RESULT =null;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).right;
		DatosConfig n0 = (DatosConfig)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)).value;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-3)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Integer n2 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 pseudo.cambiarTamaño(n1.getNumero(), n2, n0.getTipo()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-5)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // instruccion_config ::= error DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("instruccion_config",12, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // delimitador ::= DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("delimitador",13, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // delimitador ::= delimitador DELIMIT 
            {
              Object RESULT =null;

              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("delimitador",13, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // color ::= HEXADECIMAL 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		String n1 = (String)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = pseudo.hexaAColor("#"+n1.substring(1)); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("color",16, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // color ::= expr COMA expr COMA expr 
            {
              Object RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		OperadorMat n2 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n3left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n3right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n3 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = pseudo.rgbAColor(n1.getNumero(), n2.getNumero(), n3.getNumero()); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("color",16, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-4)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr MAS term 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n2 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n1.getNumero() + n2.getNumero()); 
												RESULT.setUltimo(n2.getUltimo()); RESULT.setPrimero(n1.getPrimero()); 
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.getUltimo(), "+", n2.getPrimero()});
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr MENOS term 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n2 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n1.getNumero() - n2.getNumero()); 
												RESULT.setUltimo(n2.getUltimo()); RESULT.setPrimero(n1.getPrimero()); 
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.getUltimo(), "-", n2.getPrimero()});
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= term 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("expr",0, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // term ::= term POR factor 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n2 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n1.getNumero() * n2.getNumero());
												RESULT.setUltimo(n2.getUltimo()); RESULT.setPrimero(n1.getPrimero());
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.getUltimo(), "*", n2.getPrimero()});
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // term ::= term SIGNODIVI factor 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)).value;
		int n0left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n0right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		Object n0 = (Object)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n2 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n1.getNumero() / n2.getNumero()); 
												RESULT.setUltimo(n2.getUltimo()); RESULT.setPrimero(n1.getPrimero()); 
										pseudo.agregarReporteOperador(n0left, n0right, new String[]{n1.getUltimo(), "/", n2.getPrimero()});
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // term ::= factor 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = n1; 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("term",1, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // factor ::= NUMERO 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		Integer n1 = (Integer)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n1); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // factor ::= DECIMAL 
            {
              OperadorMat RESULT =null;
		int n2left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).left;
		int n2right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()).right;
		Double n2 = (Double)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.peek()).value;
		 RESULT = new OperadorMat(n2); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // factor ::= PARENAPER expr PARENCERRA 
            {
              OperadorMat RESULT =null;
		int n1left = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).left;
		int n1right = ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).right;
		OperadorMat n1 = (OperadorMat)((java_cup.runtime.Symbol) CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-1)).value;
		 RESULT = n1; n1.setUltimo(")"); n1.setPrimero("("); 
              CUP$DiagramaParser$result = parser.getSymbolFactory().newSymbol("factor",2, ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.elementAt(CUP$DiagramaParser$top-2)), ((java_cup.runtime.Symbol)CUP$DiagramaParser$stack.peek()), RESULT);
            }
          return CUP$DiagramaParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$DiagramaParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$DiagramaParser$do_action(
    int                        CUP$DiagramaParser$act_num,
    java_cup.runtime.lr_parser CUP$DiagramaParser$parser,
    java.util.Stack            CUP$DiagramaParser$stack,
    int                        CUP$DiagramaParser$top)
    throws java.lang.Exception
    {
              return CUP$DiagramaParser$do_action_part00000000(
                               CUP$DiagramaParser$act_num,
                               CUP$DiagramaParser$parser,
                               CUP$DiagramaParser$stack,
                               CUP$DiagramaParser$top);
    }
}

}
