
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.diagramasdeflujo.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LETRASIZE = 38;
  public static final int NUMERO = 31;
  public static final int POR = 4;
  public static final int SI = 17;
  public static final int MOSTRAR = 14;
  public static final int RESTA = 27;
  public static final int ENTONCES = 19;
  public static final int TFIGURA = 36;
  public static final int PARENCERRA = 7;
  public static final int SEPARADOR = 8;
  public static final int FIN = 21;
  public static final int FINMIENTRAS = 22;
  public static final int DELIMIT = 11;
  public static final int LETRA = 35;
  public static final int MIENTRAS = 16;
  public static final int SUMA = 26;
  public static final int DECIMAL = 39;
  public static final int EOF = 0;
  public static final int SIGNODIVI = 5;
  public static final int ASIGINDI = 12;
  public static final int OPERALOGNEG = 24;
  public static final int error = 1;
  public static final int COMA = 30;
  public static final int CADENA = 42;
  public static final int MENOS = 3;
  public static final int IDENT = 41;
  public static final int DIVI = 29;
  public static final int ASIGNACION = 10;
  public static final int COLOR = 33;
  public static final int PARENAPER = 6;
  public static final int TLETRA = 37;
  public static final int DEFAULT = 9;
  public static final int OPERARELA = 43;
  public static final int LEER = 15;
  public static final int HEXADECIMAL = 40;
  public static final int HACER = 18;
  public static final int MULTI = 28;
  public static final int INICIO = 20;
  public static final int OPERALOG = 25;
  public static final int FINSI = 23;
  public static final int COLORTEXTO = 32;
  public static final int VAR = 13;
  public static final int FIGURA = 34;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "SIGNODIVI",
  "PARENAPER",
  "PARENCERRA",
  "SEPARADOR",
  "DEFAULT",
  "ASIGNACION",
  "DELIMIT",
  "ASIGINDI",
  "VAR",
  "MOSTRAR",
  "LEER",
  "MIENTRAS",
  "SI",
  "HACER",
  "ENTONCES",
  "INICIO",
  "FIN",
  "FINMIENTRAS",
  "FINSI",
  "OPERALOGNEG",
  "OPERALOG",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVI",
  "COMA",
  "NUMERO",
  "COLORTEXTO",
  "COLOR",
  "FIGURA",
  "LETRA",
  "TFIGURA",
  "TLETRA",
  "LETRASIZE",
  "DECIMAL",
  "HEXADECIMAL",
  "IDENT",
  "CADENA",
  "OPERARELA"
  };
}

